apiVersion: v1
kind: Service
metadata:
  name: staticweb
  namespace: namespace-workflow-1690866415248
spec:
  type: LoadBalancer
  selector:
    app: staticweb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080